server:
  port: 8080
spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USRNAME}
    password: ${DATASOURCE_PWD}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
